program: train_net.py
method: bayes
metric:
  name: best_segm_AP
  goal: maximize
parameters:
  mask_process_method:
    value: 'slic'
  max_training_rounds:
    value: 3
  model_weights:
    value: "/thesis/detectron2_baseline/R101-FPN/model_final_a3ec72.pkl"
  n_segments:
    values: [500, 1000, 2000]
  slic_zero:
    value: True
  threshold:
    values: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config-file"
  - "configs/wgisd_R101_with_aug_crop_new_dataset_pseudo_labels.yaml"
  - "OUTPUT_DIR"
  - "./output/sweep_pseudo_masks"
project: Mask_RCNN