program: train_net.py
method: grid
metric:
  name: new_dataset_validation_segm/AP
  goal: maximize
parameters:
  mask_process_method:
    values: ['none', 'dilation']
  max_training_rounds:
    value: 15
  model_weights:
    values: ["./output/wgisd_R101_with_aug_crop/model_final.pth",
             "/thesis/detectron2_baseline/R101-FPN/model_final_a3ec72.pkl"]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config-file"
  - "configs/wgisd_R101_with_aug_crop_new_dataset_pseudo_labels.yaml"
  - "OUTPUT_DIR"
  - "./output/sweep_naive_pseudo_masks"
project: Mask_RCNN