program: train_net.py
method: grid
metric:
  name: best_segm_AP
  goal: maximize
parameters:
  mask_process_method:
    value: 'grabcut'
  max_training_rounds:
    value: 10
  model_weights:
    value: "/thesis/detectron2_baseline/R101-FPN/model_final_a3ec72.pkl"
  experiments:
    values: [1]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config-file"
  - "configs/new_dataset_pseudo_labels.yaml"
  - "OUTPUT_DIR"
  - "./output/sweep_pseudo_masks"
project: GrapeDnT