program: train_net.py
method: grid
metric:
  name: new_dataset_validation_segm/AP
  goal: maximize
parameters:
  mask_process_method:
    values: ['none', 'dilation']
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config-file"
  - "configs/wgisd_R101_with_aug_crop_new_dataset_pseudo_labels.yaml"
  - "--generate_pseudomasks"
  - "--process_pseduomasks"
  - "OUTPUT_DIR"
  - "./output/sweep_naive_pseudo_masks"
project: Mask_RCNN