program: train_net.py
method: grid
metric:
  name: best_segm_AP
  goal: maximize
parameters:
  mask_process_method:
    value: 'grabcut'
  max_training_rounds:
    value: 1
  model_weights:
    value: "./output/wgisd_R101_with_aug_crop/model_final.pth"
  experiments:
    values: [1, 2, 3, 4, 5]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config-file"
  - "configs/wgisd_R101_with_aug_crop_new_dataset_pseudo_labels.yaml"
  - "OUTPUT_DIR"
  - "./output/sweep_pseudo_masks"
project: Mask_RCNN_experiments