program: train_net.py
method: bayes
metric:
  name: best_segm_AP
  goal: maximize
parameters:
  mask_process_method:
    value: 'slic'
  max_training_rounds:
    value: 3
  model_weights:
    values: [ "./output/wgisd_R101_with_aug_crop/model_final.pth",
              "/thesis/detectron2_baseline/R101-FPN/model_final_a3ec72.pkl" ]
  n_segments:
    values: [100, 250, 500]
  compactness:
    values: [10, 25, 50]
  slic_zero:
    values: [True, False]
  sigma:
    values: [0]
  threshold:
    values: [0.6, 0.7, 0.8]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config-file"
  - "configs/wgisd_R101_with_aug_crop_new_dataset_pseudo_labels.yaml"
  - "OUTPUT_DIR"
  - "./output/sweep_pseudo_masks"
project: Mask_RCNN