program: train_net.py
method: grid
metric:
  name: best_segm_AP
  goal: maximize
parameters:
  mask_process_method:
    value: 'none'
  max_training_rounds:
    value: 1
  model_weights:
    value: "/thesis/detectron2_baseline/R101-FPN/model_final_a3ec72.pkl"
  experiments:
    values: [1, 2, 3, 4, 5]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config-file"
  - "configs/new_dataset_video_semi_supervised.yaml"
  - "OUTPUT_DIR"
  - "./output/sweep_new_dataset_video_semi_supervised"
project: GrapeDnT