program: train_net.py
method: grid
metric:
  name: new_dataset_validation_segm/AP
  goal: maximize
parameters:
  iterative_pseudomasks_period:
    values: [10, 20, 30]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config-file"
  - "configs/sweep_aug_crop_new_dataset_pseudo_labels.yaml"
project: Mask_RCNN