program: train_net.py
method: grid
metric:
  name: best_segm_AP
  goal: maximize
parameters:
  mask_process_method:
    value: 'naive'
  max_training_rounds:
    value: 1
  model_weights:
    value: "/thesis/detectron2_baseline/R101-FPN/model_final_a3ec72.pkl"

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config-file"
  - "configs/wgisd_R101_with_aug_crop_new_dataset_pseudo_labels.yaml"
  - "OUTPUT_DIR"
  - "./output/sweep_pseudo_masks_test"
  - "MODEL.ROI_HEADS.SCORE_THRESH_TEST"
  - 0.7
project: Mask_RCNN_experiments