_BASE_: "./wgisd_R101.yaml"
DATASETS:
  TEST : ("wgisd_test", "wgisd_test_detection")
MODEL:
  WEIGHTS: "./output/wgisd_R101_with_aug_crop/model_final.pth"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.05  # default
OUTPUT_DIR: "./output/test_coco"
EVALUATOR: "coco"
