_BASE_: "./mask_rcnn_wgisd.yaml"
MODEL:
  WEIGHTS: "./output/wgisd_augmentations/model_final.pth"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.9
OUTPUT_DIR: "./output/inference"
ALBUMENTATIONS:
  LONGEST_MAX_SIZE:
    ENABLED: True
    VALUE: 1024
  PAD:
    ENABLED: True
    TARGET_HEIGHT: 1024
    TARGET_WIDTH: 1024
    VALUE: 0
    MASK_VALUE: 0