_BASE_: "./wgisd_R101.yaml"
DATASETS:
  TEST: ()
MODEL:
  WEIGHTS: "./output/wgisd_R101_aug/model_final.pth"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.9
OUTPUT_DIR: "./output/inference"
LABELS: ["Grapes"]
COLORS: [[240, 50, 200]]
