_BASE_: "./wgisd_R101.yaml"
DATASETS:
  TEST: ()
MODEL:
  WEIGHTS: "./output/wgisd_R101_with_aug/model_final.pth"
OUTPUT_DIR: "./output/inference/visualization"
LABELS: ["Grapes"]
COLORS: [[240, 50, 200]]
