_BASE_: "./mask_rcnn_wgisd_augmentations.yaml"
DATASETS:
  TEST : ("wgisd_augmented_test_detection",)
MODEL:
  WEIGHTS: "./output/wgisd_augmentations/model_final.pth"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.00001
OUTPUT_DIR: "./output/wgisd_augmentations_test"
EVALUATOR: "pascal"
