_BASE_: "./Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN : ("wgisd_train",)
  TEST : ("wgisd_valid",)
DATALOADER:
  NUM_WORKERS : 4
INPUT:
  MASK_FORMAT : "bitmask"
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1024
  RANDOM_FLIP: "horizontal"
SOLVER:
  IMS_PER_BATCH : 1
  BASE_LR : 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: []
  MAX_ITER: 8800
  CHECKPOINT_PERIOD : 88
  WARMUP_ITERS : 0
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  WEIGHTS: "/thesis/detectron2_baseline/model_final_f10217.pkl"
  ROI_HEADS:
    NUM_CLASSES : 1
TEST:
  EVAL_PERIOD: 88
OUTPUT_DIR: "../output/wgisd_paper"
