_BASE_: "./Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN : ("wgisd_train",)
  TEST : ("wgisd_valid",)
DATALOADER:
  NUM_WORKERS : 2
INPUT:
  MASK_FORMAT : "bitmask"
SOLVER:
  IMS_PER_BATCH : 4
  BASE_LR : 0.0025
  STEPS: (367, 489)
  MAX_ITER: 550
  CHECKPOINT_PERIOD : 5
  WARMUP_ITERS : 50
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/137849600/model_final_f10217.pkl"
  ROI_HEADS:
    NUM_CLASSES : 1
TEST:
  EVAL_PERIOD: 5
OUTPUT_DIR: "../output/exp1"
