_BASE_: "./mask_rcnn_wgisd.yaml"
DATASETS:
  TEST : ("wgisd_augmented_test",)
MODEL:
  WEIGHTS: "./output/wgisd_paper/model_final.pth"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.9
OUTPUT_DIR: "./output/wgisd_paper_test"
