_BASE_: "./wgisd_R101.yaml"
DATASETS:
  # 2492 (88 + 94 + 417 + 424 + 599 + 600 + 270)
  TRAIN: ("wgisd_train", "new_dataset_train", "closeup1", "closeup2", "video1", "video2", "video3")
SOLVER:
  MAX_ITER: 249200  # train for 100 epochs
  CHECKPOINT_PERIOD: 2492  # checkpoint every epoch
  ITERS_PER_EPOCH: 2492
  MAX_TRAINING_ROUNDS: 1
TEST:
  EVAL_PERIOD: 2492  # evaluate every epoch
OUTPUT_DIR: "./output/new_dataset_video_pseudo_labels"
SEED: 42
PSEUDOMASKS:
  GENERATE: True
  DATASET_NAME: ["new_dataset_train", "closeup1", "closeup2", "video1", "video2", "video3"]
  DATA_FOLDER: ["/thesis/datasets/new_dataset/train",
                "/thesis/datasets/videos/closeup1/",
                "/thesis/datasets/videos/closeup2/",
                "/thesis/datasets/videos/video1/",
                "/thesis/datasets/videos/video2/",
                "/thesis/datasets/videos/video3/"]
  PROCESS_METHOD: "none"