_BASE_: "./wgisd_R101.yaml"
DATASETS:
  # 182 (88 + 94)
  TRAIN: ("wgisd_train", "new_dataset_semi_supervised")
SOLVER:
  MAX_ITER: 18200  # train for 100 epochs
  CHECKPOINT_PERIOD: 182  # checkpoint every epoch
  ITERS_PER_EPOCH: 182
  MAX_TRAINING_ROUNDS: 1
TEST:
  EVAL_PERIOD: 182  # evaluate every epoch
OUTPUT_DIR: "./output/semi_supervised_pseudo_labels"
SEED: 42
PSEUDOMASKS:
  GENERATE: True
  DATASET_NAME: ["new_dataset_semi_supervised"]
  DATA_FOLDER: ["/thesis/datasets/new_dataset_semi_supervised"]
  LABELS_FOLDER: [ "/thesis/datasets/new_dataset_semi_supervised" ]
  PROCESS_METHOD: "none"