_BASE_: "./wgisd_R101.yaml"
DATASETS:
  # 781 (88 + 94 + 599)
  TRAIN: ("wgisd_train", "new_dataset_semi_supervised", "video")
SOLVER:
  MAX_ITER: 78100  # train for 100 epochs
  CHECKPOINT_PERIOD: 781  # checkpoint every epoch
  ITERS_PER_EPOCH: 781
  MAX_TRAINING_ROUNDS: 1
TEST:
  EVAL_PERIOD: 781  # evaluate every epoch
OUTPUT_DIR: "./output/semi_supervised_pseudo_labels"
SEED: 42
PSEUDOMASKS:
  GENERATE: True
  DATASET_NAME: ["new_dataset_semi_supervised", "video"]
  DATA_FOLDER: ["/thesis/datasets/new_dataset_semi_supervised",
                "/thesis/datasets/video"]
  LABELS_FOLDER: ["/thesis/datasets/new_dataset_semi_supervised",
                  "/thesis/datasets/video"]
  PROCESS_METHOD: "none"