_BASE_: "./wgisd_R101_with_aug.yaml"
DATASETS:
  TRAIN : ("new_dataset_test",)
  TEST : ("new_dataset_validation",)
MODEL:
  WEIGHTS: "./output/wgisd_R101_with_aug_crop/model_final.pth"
SOLVER:
  MAX_ITER: 11300 # 17300  # 8800 + 8500
  CHECKPOINT_PERIOD: 25
TEST:
  EVAL_PERIOD: 25
OUTPUT_DIR: "./output/R101_fine_tuning"
