_BASE_: "./wgisd_R101_with_aug_crop.yaml"
DATASETS:
  TRAIN : ("new_dataset_train",)
  TEST : ("new_dataset_validation",)
MODEL:
  WEIGHTS: "./output/wgisd_R101_with_aug_crop/model_final.pth"
SOLVER:
  MAX_ITER: 17300  # 8800 + 8500
  CHECKPOINT_PERIOD: 85
TEST:
  EVAL_PERIOD: 85
OUTPUT_DIR: "./output/R101_fine_tuning"
