_BASE_: "./wgisd_R101.yaml"
DATASETS:
  TRAIN : ("new_dataset_train",)
  TEST : ("new_dataset_validation",)
MODEL:
  WEIGHTS: "./output/wgisd_R101/model_final.pth"
SOLVER:
  MAX_ITER: 18200  # 8800 + 9400
  CHECKPOINT_PERIOD: 94
TEST:
  EVAL_PERIOD: 94
OUTPUT_DIR: "./output/R101_fine_tuning"
