_BASE_: "./wgisd_R101_with_aug.yaml"
DATASETS:
  TRAIN : ("new_dataset_train",)
  TEST : ("new_dataset_validation",)
MODEL:
  WEIGHTS: "./output/wgisd_R101_with_aug/model_final.pth"
OUTPUT_DIR: "./output/test"