_BASE_: "./wgisd_R101.yaml"
DATASETS:
  # 687 (88 + 599)
  TRAIN: ("wgisd_train", "video")
SOLVER:
  MAX_ITER: 68700  # train for 100 epochs
  CHECKPOINT_PERIOD: 687  # checkpoint every epoch
  ITERS_PER_EPOCH: 687
  MAX_TRAINING_ROUNDS: 1
TEST:
  EVAL_PERIOD: 687  # evaluate every epoch
OUTPUT_DIR: "./output/video_pseudo_labels"
SEED: 42
PSEUDOMASKS:
  GENERATE: True
  DATASET_NAME: ["video"]
  DATA_FOLDER: ["/thesis/datasets/video"]
  LABELS_FOLDER: ["/thesis/datasets/video"]
  PROCESS_METHOD: "grabcut"