_BASE_: "./wgisd_R101.yaml"
DATASETS:
  # 2398 (88 + 417 + 424 + 599 + 600 + 270)
  TRAIN: ("wgisd_train", "closeup1", "closeup2", "video1", "video2", "video3")
SOLVER:
  MAX_ITER: 239800  # train for 100 epochs
  CHECKPOINT_PERIOD: 2398  # checkpoint every epoch
  ITERS_PER_EPOCH: 2398
  MAX_TRAINING_ROUNDS: 1
TEST:
  EVAL_PERIOD: 2398  # evaluate every epoch
OUTPUT_DIR: "./output/video_pseudo_labels"
SEED: 42
PSEUDOMASKS:
  GENERATE: True
  DATASET_NAME: ["closeup1", "closeup2", "video1", "video2", "video3" ]
  DATA_FOLDER: ["/thesis/datasets/videos/closeup1/",
                "/thesis/datasets/videos/closeup2/",
                "/thesis/datasets/videos/video1/",
                "/thesis/datasets/videos/video2/",
                "/thesis/datasets/videos/video3/"]
  PROCESS_METHOD: "none"