_BASE_: "./wgisd_R101.yaml"
DATASETS:
  # 687 (88 + 599)
  TRAIN: ("wgisd_train", "video")
SOLVER:
  MAX_ITER: 68700  # train for 100 epochs
  CHECKPOINT_PERIOD: 687  # checkpoint every epoch
  ITERS_PER_EPOCH: 687
  MAX_TRAINING_ROUNDS: 1
TEST:
  EVAL_PERIOD: 687  # evaluate every epoch
OUTPUT_DIR: "./output/video_pseudo_labels"
SEED: 42
PSEUDOMASKS:
  GENERATE: True
  DATASET_NAME: ["video", "FeaturesLabels_skip2", "FeaturesLabels_skip5", "FeaturesLabels_skip8",
                 "FeaturesLabels_skip11", "FeaturesLabels_skip14", "SfmLabels_skip2", "SfmLabels_skip5",
                 "SfmLabels_skip8", "SfmLabels_skip11", "SfmLabels_skip14"]
  DATA_FOLDER: ["/thesis/datasets/video",
                "/thesis/datasets/video",  # Features
                "/thesis/datasets/video",
                "/thesis/datasets/video",
                "/thesis/datasets/video",
                "/thesis/datasets/video",
                "/thesis/datasets/video",  # Sfm
                "/thesis/datasets/video",
                "/thesis/datasets/video",
                "/thesis/datasets/video",
                "/thesis/datasets/video"]
  LABELS_FOLDER: ["/thesis/datasets/video",
                  "./datasets_skip/FeaturesLabels_skip2",
                  "./datasets_skip/FeaturesLabels_skip5",
                  "./datasets_skip/FeaturesLabels_skip8",
                  "./datasets_skip/FeaturesLabels_skip11",
                  "./datasets_skip/FeaturesLabels_skip14",
                  "./datasets_skip/SfmLabels_skip2",
                  "./datasets_skip/SfmLabels_skip5",
                  "./datasets_skip/SfmLabels_skip8",
                  "./datasets_skip/SfmLabels_skip11",
                  "./datasets_skip/SfmLabels_skip14"]
  PROCESS_METHOD: "none"