_BASE_: "./wgisd_R101_with_aug_crop.yaml"
DATASETS:
  TRAIN: ("wgisd_train", "full_test_video")  # 1984 (88+1896)
SOLVER:
  MAX_ITER: 198400  # train for 100 epochs
  CHECKPOINT_PERIOD: 1984  # checkpoint every epoch
  ITERS_PER_EPOCH: 1984
  MAX_TRAINING_ROUNDS: 1
TEST:
  EVAL_PERIOD: 1984  # evaluate every epoch
OUTPUT_DIR: "./output/wgisd_R101_with_aug_crop_pseudo_labels"
SEED: -1
PSEUDOMASKS:
  GENERATE: True
  IDS_TXT: ["/thesis/full_test_video/ids.txt"]
  DATA_FOLDER: ["/thesis/full_test_video/data"]
  DEST_FOLDER: ["pseudo_masks/full_test_video"]
  INITIAL_WEIGHTS: "./output/wgisd_R101_with_aug_crop/model_final.pth"
  PROCESS_METHOD: "grabcut"
  GRABCUT:
    MEDIAN_BLUR: 25
  SLIC:
    SLIC_ZERO: False
    N_SEGMENTS: 2000
    COMPACTNESS: 0.1
    SIGMA: 0
    THRESHOLD: 0.7