_BASE_: "./wgisd_R101_with_aug_crop.yaml"
DATASETS:
  TRAIN : ("wgisd_train", "new_dataset_train")  # 305
SOLVER:
  MAX_ITER: 17300  # train for 100 epochs
  CHECKPOINT_PERIOD: 173  # checkpoint every epoch
TEST:
  EVAL_PERIOD: 173  # evaluate every epoch
OUTPUT_DIR: "./output/wgisd_R101_with_aug_crop_new_dataset_pseudo_labels"