_BASE_: "./Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN : ("wgisd_train",)
  TEST : ("wgisd_valid",)
DATALOADER:
  NUM_WORKERS : 4
INPUT:
  MASK_FORMAT : "bitmask"
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1024
  RANDOM_FLIP: "horizontal"
SOLVER:
  IMS_PER_BATCH : 8
  BASE_LR : 0.008
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  STEPS: []
  MAX_ITER: 1100
  CHECKPOINT_PERIOD : 1
  WARMUP_ITERS : 0
MODEL:
  MASK_ON: True
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 101
  WEIGHTS: "/thesis/detectron2_baseline/R101-FPN/model_final_a3ec72.pkl"
  ROI_HEADS:
    NUM_CLASSES : 1
TEST:
  EVAL_PERIOD: 11
OUTPUT_DIR: "./output/wgisd_R101"
SEED: 42
ALBUMENTATIONS:
  GAUSSIAN_BLUR:
    ENABLED: False
  GAUSSIAN_NOISE:
    ENABLED: False
  RANDOM_BRIGHTNESS_CONTRAST:
    ENABLED: False
  PIXEL_DROPOUT:
    ENABLED: False
    DROPOUT_MIN: 0.0
    DROPOUT_MAX: 0.05
EVALUATOR: "coco"