_BASE_: "./wgisd_R101.yaml"
OUTPUT_DIR: "./output/wgisd_R101_aug"
ALBUMENTATIONS:
  HORIZONTAL_FLIP:
    ENABLED: True
  GAUSSIAN_BLUR:
    ENABLED: True
  GAUSSIAN_NOISE:
    ENABLED: True
  RANDOM_BRIGHTNESS_CONTRAST:
    ENABLED: True
  PIXEL_DROPOUT:
    ENABLED: True
    DROPOUT_PROBABILITY: [0.0, 0.05]