_BASE_: "./wgisd_R101_with_aug_crop.yaml"
DATASETS:
  TRAIN: ("wgisd_train", "new_dataset_train")  # 173
SOLVER:
  MAX_ITER: 17300  # train for 100 epochs
  CHECKPOINT_PERIOD: 173  # checkpoint every epoch
  ITERS_PER_EPOCH: 173
  MAX_TRAINING_ROUNDS: 1
TEST:
  EVAL_PERIOD: 173  # evaluate every epoch
OUTPUT_DIR: "./output/wgisd_R101_with_aug_crop_new_dataset_pseudo_labels"
PSEUDOMASKS:
  GENERATE: True
  IDS_TXT: ["/thesis/new_dataset/train/train.txt"]
  DATA_FOLDER: ["/thesis/new_dataset/train"]
  DEST_FOLDER: ["pseudo_masks/new_dataset"]
  INITIAL_WEIGHTS: "./output/wgisd_R101_with_aug_crop/model_final.pth"
  PROCESS_METHOD: "none"
  SLIC:
    SLIC_ZERO: False
    N_SEGMENTS: 100
    COMPACTNESS: 10
    SIGMA: 0
    THRESHOLD: 0.1