_BASE_: "./wgisd_R101_with_aug_crop.yaml"
DATASETS:
  TRAIN : ("wgisd_train", "wgisd_pseudo_labels")
SOLVER:
  MAX_ITER: 22000
  CHECKPOINT_PERIOD: 220
TEST:
  EVAL_PERIOD: 220
OUTPUT_DIR: "./output/wgisd_R101_with_aug_crop_pseudo_labels"