_BASE_: "./Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN : ("wgisd_train",)
  TEST : ("wgisd_valid", "new_dataset_validation")
DATALOADER:
  NUM_WORKERS : 4
INPUT:
  MASK_FORMAT : "bitmask"
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1024
  RANDOM_FLIP: "horizontal"
SOLVER:
  IMS_PER_BATCH : 1
  BASE_LR : 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  STEPS: []
  MAX_ITER: 8800
  CHECKPOINT_PERIOD : 88
  WARMUP_ITERS : 0
  ITERS_PER_EPOCH: 88
  MAX_TRAINING_ROUNDS: 1
MODEL:
  MASK_ON: True
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 101
  WEIGHTS: "/thesis/detectron2_baseline/R101-FPN/model_final_a3ec72.pkl"
  ROI_HEADS:
    NUM_CLASSES : 1
TEST:
  EVAL_PERIOD: 88
OUTPUT_DIR: "./output/wgisd_R101"
SEED: 42
ALBUMENTATIONS:
  GAUSSIAN_BLUR:
    ENABLED: False
  GAUSSIAN_NOISE:
    ENABLED: False
  RANDOM_BRIGHTNESS_CONTRAST:
    ENABLED: False
  PIXEL_DROPOUT:
    ENABLED: False
    DROPOUT_MIN: 0.0
    DROPOUT_MAX: 0.05
PSEUDOMASKS:
  GENERATE: False
  IDS_TXT: ["/thesis/new_dataset/train/train.txt"]
  DATA_FOLDER: ["/thesis/new_dataset/train"]
  DEST_FOLDER: ["pseudo_masks/new_dataset"]
  INITIAL_WEIGHTS: "./output/wgisd_R101_with_aug_crop/model_final.pth"
  PROCESS_METHOD: "none"
  GRABCUT:
    DILATION: True
    MEDIAN_BLUR: 25
  SLIC:
    SLIC_ZERO: False
    N_SEGMENTS: 2000
    COMPACTNESS: 0.1
    SIGMA: 0
    THRESHOLD: 0.1
EVALUATOR: "coco"