_BASE_: "./wgisd_R50.yaml"
OUTPUT_DIR: "./output/wgisd_R50_aug"
ALBUMENTATIONS:
  GAUSSIAN_BLUR:
    ENABLED: True
  GAUSSIAN_NOISE:
    ENABLED: True
  RANDOM_BRIGHTNESS_CONTRAST:
    ENABLED: True
  PIXEL_DROPOUT:
    ENABLED: True
    DROPOUT_MIN: 0.0
    DROPOUT_MAX: 0.05
