_BASE_: "./wgisd_R101_with_aug_crop.yaml"
DATASETS:
  TRAIN: ("wgisd_train", "new_dataset_train", "wgisd_pseudo_labels")  # 305
SOLVER:
  MAX_ITER: 30500  # train for 100 epochs
  CHECKPOINT_PERIOD: 305  # checkpoint every epoch
  ITERS_PER_EPOCH: 305
  MAX_TRAINING_ROUNDS: 1
TEST:
  EVAL_PERIOD: 305  # evaluate every epoch
OUTPUT_DIR: "./output/wgisd_R101_with_aug_crop_pseudo_labels"
PSEUDOMASKS:
  IDS_TXT: ["/thesis/new_dataset/train/train.txt", "/thesis/wgisd/train_without_masked_train_and_valid_ids.txt"]
  DATA_FOLDER: ["/thesis/new_dataset/train", "/thesis/wgisd/data"]
  DEST_FOLDER: ["pseudo_masks/new_dataset", "pseudo_masks/wgisd"]
  INITIAL_WEIGHTS: "./output/wgisd_R101_with_aug_crop/model_final.pth"
  PROCESS_METHOD: "none"