_BASE_: "./wgisd_R101.yaml"
DATASETS:
  # 2398 (88 + 417 + 424 + 599 + 600 + 270)
  TRAIN: ("wgisd_train", "closeup1", "closeup2", "video1", "video2", "video3")
SOLVER:
  MAX_ITER: 239800  # train for 100 epochs
  CHECKPOINT_PERIOD: 2398  # checkpoint every epoch
  ITERS_PER_EPOCH: 2398
  MAX_TRAINING_ROUNDS: 1
TEST:
  EVAL_PERIOD: 2398  # evaluate every epoch
OUTPUT_DIR: "./output/wgisd_R101_with_aug_crop_pseudo_labels_2"
SEED: -1
PSEUDOMASKS:
  GENERATE: True
  IDS_TXT: ["/thesis/videos/closeup1/ids.txt",
            "/thesis/videos/closeup2/ids.txt",
            "/thesis/videos/video1/ids.txt",
            "/thesis/videos/video2/ids.txt",
            "/thesis/videos/video3/ids.txt"]
  DATASET_NAME: ["closeup1", "closeup2", "video1", "video2", "video3" ]
  DATA_FOLDER: ["/thesis/videos/closeup1/",
                "/thesis/videos/closeup2/",
                "/thesis/videos/video1/",
                "/thesis/videos/video2/",
                "/thesis/videos/video3/"]
  INITIAL_WEIGHTS: "./output/wgisd_R101_with_aug_crop/model_final.pth"
  PROCESS_METHOD: "none"