_BASE_: "./wgisd_R50.yaml"
DATASETS:
  TEST : ("wgisd_augmented_test", "wgisd_augmented_test_detection")
MODEL:
  WEIGHTS: "./output/wgisd_R50_aug/model_final.pth"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.9
OUTPUT_DIR: "./output/wgisd_R50_aug_test"
EVALUATOR: "pascal"
