_BASE_: "./wgisd_R101_with_aug_crop.yaml"
DATASETS:
  TRAIN : ("wgisd_train", "wgisd_pseudo_labels", "new_dataset_train")  # 305
SOLVER:
  MAX_ITER: 30500  # train for 100 epochs
  CHECKPOINT_PERIOD: 3050  # checkpoint every 10 epochs
TEST:
  EVAL_PERIOD: 305  # evaluate every epoch
OUTPUT_DIR: "./output/wgisd_R101_with_aug_crop_pseudo_labels"