_BASE_: "./Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN : ("wgisd_train",)
  TEST : ("wgisd_augmented_valid",)
DATALOADER:
  NUM_WORKERS : 8
INPUT:
  MASK_FORMAT : "bitmask"
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1024
  RANDOM_FLIP: "horizontal"
SOLVER:
  IMS_PER_BATCH : 1
  BASE_LR : 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: []
  MAX_ITER: 8800
  CHECKPOINT_PERIOD : 88
  WARMUP_ITERS : 0
MODEL:
  MASK_ON: True
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 101
  WEIGHTS: "/thesis/detectron2_baseline/R101-FPN/model_final_a3ec72.pkl"
  ROI_HEADS:
    NUM_CLASSES : 1
TEST:
  EVAL_PERIOD: 88
OUTPUT_DIR: "./output/wgisd_R101"
SEED: 42
ALBUMENTATIONS:
  LONGEST_MAX_SIZE:
    ENABLED: True
    VALUE: 1024
  PAD:
    ENABLED: True
    TARGET_HEIGHT: 1024
    TARGET_WIDTH: 1024
    VALUE: 0
    MASK_VALUE: 0
  HORIZONTAL_FLIP:
    ENABLED: False
  GAUSSIAN_BLUR:
    ENABLED: False
  GAUSSIAN_NOISE:
    ENABLED: False
  RANDOM_BRIGHTNESS_CONTRAST:
    ENABLED: False
  PIXEL_DROPOUT:
    ENABLED: False
    DROPOUT_PROBABILITY: [0.0, 0.05]
EVALUATOR: "coco"